### ISSUE TITLE
Text hidden by navbar

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/LDLT-reading-room#1]
When a user clicks on a link to an item in the bibliography, the target of the link is buried under the navigation bar. This could probably be fixed with the answer at [https://stackoverflow.com/a/13117744](https://stackoverflow.com/a/13117744).

**Comment by hcayless** [comment]
Fixed in 20264ea27170bdc3c94d1c21766b99c6bb64aff8.
